name: Update README Benchmarks
permissions:
  contents: write
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas tabulate
      - name: Run update script
        run: |
          python update_readme.py
      - name: Commit & Push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md data/benchmark.json
          git commit -m 'chore: update benchmarks [auto]' || echo 'No changes to commit'
          git pull --rebase origin main
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
